In [ ]:
from cell_eval import MetricsEvaluator
from cell_eval.data import build_random_anndata, downsample_cells

adata_real = build_random_anndata()
adata_pred = downsample_cells(adata_real, fraction=0.5)
evaluator = MetricsEvaluator(
    adata_pred=adata_pred,
    adata_real=adata_real,
    control_pert="control",
    pert_col="perturbation",
    num_threads=64,
)
(results, agg_results) = evaluator.compute(include_baselines = ["pert-mean", "cell-type-mean", "nearest-cell-type-transfer"])

WARNING:cell_eval._evaluator:Output directory ./cell-eval-outdir already exists, potential overwrite occurring
INFO:cell_eval.utils:Data appears to be log1p normalized (decimals detected, range [0.00, 5.46])
INFO:cell_eval._evaluator:Input is found to be log-normalized already - skipping transformation.
INFO:cell_eval.utils:Data appears to be log1p normalized (decimals detected, range [0.00, 5.44])
INFO:cell_eval._evaluator:Input is found to be log-normalized already - skipping transformation.
INFO:cell_eval._evaluator:Computing DE for real data
INFO:cell_eval._evaluator:Using the following pdex kwargs: {'reference': 'control', 'groupby_key': 'perturbation', 'num_workers': 64, 'batch_size': 100, 'metric': 'wilcoxon', 'is_log1p': True, 'as_polars': True}
INFO:pdex._single_cell:Log1p status: True
INFO:pdex._single_cell:Precomputing masks for each target gene
Identifying target masks: 100%|██████████| 11/11 [00:00<00:00, 9967.02it/s]
INFO:pdex._single_cell:Precomputing variable indices for each feature
Identifying variable indices: 100%|██████████| 100/100 [00:00<00:00, 1754938.91it/s]
INFO:pdex._single_cell:Creating shared memory matrix for parallel computing
INFO:pdex._single_cell:Creating generator of all combinations: N=1100
INFO:pdex._single_cell:Creating generator of all batches: N=12
INFO:pdex._single_cell:Initializing parallel processing pool with 64 workers
INFO:pdex._single_cell:Processing batches
Processing batches:  92%|█████████▏| 11/12 [00:00<00:00, 122.13it/s]
INFO:pdex._single_cell:Flattening results
INFO:pdex._single_cell:Closing shared memory pool
INFO:cell_eval._evaluator:Writing real DE results to: real_de.csv
INFO:cell_eval._evaluator:Computing DE for pred data
INFO:cell_eval._evaluator:Using the following pdex kwargs: {'reference': 'control', 'groupby_key': 'perturbation', 'num_workers': 64, 'batch_size': 100, 'metric': 'wilcoxon', 'is_log1p': True, 'as_polars': True}
INFO:pdex._single_cell:Log1p status: True
INFO:pdex._single_cell:Precomputing masks for each target gene
Identifying target masks: 100%|██████████| 11/11 [00:00<00:00, 13900.98it/s]
INFO:pdex._single_cell:Precomputing variable indices for each feature
Identifying variable indices: 100%|██████████| 100/100 [00:00<00:00, 1987821.80it/s]
INFO:pdex._single_cell:Creating shared memory matrix for parallel computing
INFO:pdex._single_cell:Creating generator of all combinations: N=1100
INFO:pdex._single_cell:Creating generator of all batches: N=12
INFO:pdex._single_cell:Initializing parallel processing pool with 64 workers
INFO:pdex._single_cell:Processing batches
Processing batches:  92%|█████████▏| 11/12 [00:00<00:00, 127.98it/s]
INFO:pdex._single_cell:Flattening results
INFO:pdex._single_cell:Closing shared memory pool
INFO:cell_eval._evaluator:Writing pred DE results to: pred_de.csv
INFO:cell_eval._types._de:Checking DE data integrity... (real)
INFO:cell_eval._types._de:DE data integrity check complete. (real)
INFO:cell_eval._types._de:Checking DE data integrity... (pred)
INFO:cell_eval._types._de:DE data integrity check complete. (pred)
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_N'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_50'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_100'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_200'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_500'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_N'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_50'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_100'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_200'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_500'
INFO:cell_eval._pipeline._runner:Computing metric 'de_spearman_sig'
INFO:cell_eval._pipeline._runner:Computing metric 'de_direction_match'
INFO:cell_eval._pipeline._runner:Computing metric 'de_spearman_lfc_sig'
INFO:cell_eval._pipeline._runner:Computing metric 'de_sig_genes_recall'
INFO:cell_eval._pipeline._runner:Computing metric 'de_nsig_counts'
INFO:cell_eval._pipeline._runner:Computing metric 'pr_auc'
INFO:cell_eval._pipeline._runner:Computing metric 'roc_auc'
INFO:cell_eval._pipeline._runner:Computing metric 'pearson_delta'
INFO:cell_eval._types._anndata:Building pseudobulk embeddings for real anndata on: .X
INFO:cell_eval._types._anndata:Building pseudobulk embeddings for predicted anndata on: .X
Iterating over perturbations...: 100%|██████████| 10/10 [00:00<00:00, 3119.60it/s]
INFO:cell_eval._pipeline._runner:Computing metric 'mse'
Iterating over perturbations...: 100%|██████████| 10/10 [00:00<00:00, 4223.45it/s]
INFO:cell_eval._pipeline._runner:Computing metric 'mae'
Iterating over perturbations...: 100%|██████████| 10/10 [00:00<00:00, 6055.01it/s]
INFO:cell_eval._pipeline._runner:Computing metric 'mse_delta'
Iterating over perturbations...: 100%|██████████| 10/10 [00:00<00:00, 5987.59it/s]
INFO:cell_eval._pipeline._runner:Computing metric 'mae_delta'
Iterating over perturbations...: 100%|██████████| 10/10 [00:00<00:00, 6467.70it/s]
INFO:cell_eval._pipeline._runner:Computing metric 'discrimination_score_l1'
Iterating over perturbations...: 100%|██████████| 10/10 [00:00<00:00, 71453.22it/s]
Iterating over perturbations...: 100%|██████████| 10/10 [00:00<00:00, 75983.77it/s]
INFO:cell_eval._pipeline._runner:Computing metric 'discrimination_score_l2'
Iterating over perturbations...: 100%|██████████| 10/10 [00:00<00:00, 68089.35it/s]
Iterating over perturbations...: 100%|██████████| 10/10 [00:00<00:00, 83886.08it/s]
INFO:cell_eval._pipeline._runner:Computing metric 'discrimination_score_cosine'
Iterating over perturbations...: 100%|██████████| 10/10 [00:00<00:00, 75846.37it/s]
Iterating over perturbations...: 100%|██████████| 10/10 [00:00<00:00, 84733.41it/s]
INFO:cell_eval._pipeline._runner:Computing metric 'pearson_edistance'
INFO:cell_eval.metrics._anndata:Precomputing sigma for control data (real)
INFO:cell_eval.metrics._anndata:Precomputing sigma for control data (pred)
Iterating over perturbations...: 100%|██████████| 10/10 [00:00<00:00, 416.95it/s]
INFO:cell_eval._pipeline._runner:Computing metric 'clustering_agreement'
INFO:cell_eval._evaluator:Writing perturbation level metrics to ./cell-eval-outdir/results.csv
INFO:cell_eval._evaluator:Writing aggregate metrics to ./cell-eval-outdir/agg_results.csv
INFO:cell_eval._types._de:Checking DE data integrity... (real)
INFO:cell_eval._types._de:DE data integrity check complete. (real)
INFO:cell_eval._types._de:Checking DE data integrity... (pred)
INFO:cell_eval._types._de:DE data integrity check complete. (pred)
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_N'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_50'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_100'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_200'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_500'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_N'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_50'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_100'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_200'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_500'
INFO:cell_eval._pipeline._runner:Computing metric 'de_spearman_lfc_sig'
INFO:cell_eval._pipeline._runner:Computing metric 'de_direction_match'
INFO:cell_eval._evaluator:Writing baseline metrics to ./cell-eval-outdir/pert-mean_results.csv
INFO:cell_eval._evaluator:Writing baseline aggregate metrics to ./cell-eval-outdir/pert-mean_agg_results.csv
INFO:cell_eval._types._de:Checking DE data integrity... (real)
INFO:cell_eval._types._de:DE data integrity check complete. (real)
INFO:cell_eval._types._de:Checking DE data integrity... (pred)
INFO:cell_eval._types._de:DE data integrity check complete. (pred)
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_N'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_50'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_100'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_200'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_500'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_N'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_50'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_100'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_200'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_500'
INFO:cell_eval._pipeline._runner:Computing metric 'de_spearman_lfc_sig'
INFO:cell_eval._pipeline._runner:Computing metric 'de_direction_match'
INFO:cell_eval._evaluator:Writing baseline metrics to ./cell-eval-outdir/cell-type-mean_results.csv
INFO:cell_eval._evaluator:Writing baseline aggregate metrics to ./cell-eval-outdir/cell-type-mean_agg_results.csv
INFO:cell_eval._types._de:Checking DE data integrity... (real)
INFO:cell_eval._types._de:DE data integrity check complete. (real)
INFO:cell_eval._types._de:Checking DE data integrity... (pred)
INFO:cell_eval._types._de:DE data integrity check complete. (pred)
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_N'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_50'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_100'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_200'
INFO:cell_eval._pipeline._runner:Computing metric 'overlap_at_500'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_N'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_50'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_100'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_200'
INFO:cell_eval._pipeline._runner:Computing metric 'precision_at_500'
INFO:cell_eval._pipeline._runner:Computing metric 'de_spearman_lfc_sig'
INFO:cell_eval._pipeline._runner:Computing metric 'de_direction_match'
INFO:cell_eval._evaluator:Writing baseline metrics to ./cell-eval-outdir/nearest-cell-type-transfer_results.csv
INFO:cell_eval._evaluator:Writing baseline aggregate metrics to ./cell-eval-outdir/nearest-cell-type-transfer_agg_results.csv
INFO:cell_eval._evaluator:Writing model comparison metrics to ./cell-eval-outdir/model_comparison_results.csv

In [7]:
comp = pd.read_csv('/home/cachris/ctc/projects/state_ngn2/cell-eval/cell-eval-outdir/model_comparison_results.csv')
comp.set_index('model', inplace=True)

In [4]:
import pandas as pd

In [8]:
comp['pearson_delta']

model
pred                 0.697042
pertmean             0.802161
contextmean          0.791090
celltype_transfer    0.780095
Name: pearson_delta, dtype: float64

In [9]:
comp.head()

,overlap_at_N,overlap_at_50,overlap_at_100,overlap_at_200,overlap_at_500,precision_at_N,precision_at_50,precision_at_100,precision_at_200,precision_at_500,...,mae_delta,discrimination_score_l1,discrimination_score_l2,discrimination_score_cosine,pearson_edistance,clustering_agreement,de_spearman_lfc_sig,de_direction_match,de_spearman_lfc,spearman_effect_size
model,,,,,,,,,,,,,,,,,,,,,
pred,0.00000,0.000,0.00000,0.00000,0.00000,0.000,0.000,0.000,0.000,0.000,...,0.120673,1.0,1.0,1.0,0.411936,0.44875,NaN,NaN,NaN,NaN
pertmean,0.99697,0.684,0.99697,0.99697,0.99697,0.997,0.684,0.997,0.997,0.997,...,NaN,NaN,NaN,NaN,NaN,NaN,0.799662,0.815394,0.798527,0.504342
contextmean,0.99697,0.668,0.99697,0.99697,0.99697,0.997,0.668,0.997,0.997,0.997,...,NaN,NaN,NaN,NaN,NaN,NaN,0.788559,0.809384,0.787243,0.488024
celltype_transfer,0.99697,0.686,0.99697,0.99697,0.99697,0.997,0.686,0.997,0.997,0.997,...,NaN,NaN,NaN,NaN,NaN,NaN,0.780845,0.819414,0.780787,0.458419

In [9]:
comp.iloc[:,10:20]

,precision_at_500,de_spearman_sig,de_nsig_counts_real,de_nsig_counts_pred,pr_auc,roc_auc,pearson_delta,mse,mae,mse_delta
0,0.000,1.0,0.0,0.0,NaN,NaN,0.697042,0.010322,0.080152,0.02424
1,0.997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
comp['pearson_delta']

0    0.697042
1         NaN
2         NaN
3         NaN
Name: pearson_delta, dtype: float64

In [12]:
comp['de_spearman_sig']

0    1.0
1    NaN
2    NaN
3    NaN
Name: de_spearman_sig, dtype: float64